# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [15]:
print("Numpy version:", np.__version__)
print("Numpy configurations:", np.__config__)


Numpy version: 2.0.1
Numpy configurations: <module 'numpy.__config__' from 'c:\\Users\\VORPC\\anaconda3\\envs\\env1\\lib\\site-packages\\numpy\\__config__.py'>


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [30]:
a = np.random.randint(10, size=(2,3,5))




### 4. Print a.


In [31]:
print(a)


[[[4 9 4 9 8]
  [6 1 6 3 3]
  [9 7 4 3 1]]

 [[6 3 2 4 6]
  [0 9 9 9 8]
  [8 6 5 4 6]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [44]:
b = np.ones((5,2,3))



### 6. Print b.


In [45]:
print(b)



[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [34]:
a.size == b.size


True


### 8. Are you able to add a and b? Why or why not?


In [38]:
 a + b 
#because they are not allight 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [52]:
c = np.transpose(b,(1,2,0))
print(c)
print("Original shape of b:", b.shape)
print("Transposed shape of c:", c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
Original shape of b: (5, 2, 3)
Transposed shape of c: (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [53]:
d = a + c 



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [54]:
print(a)
print (d)

#same values + 1 

[[[4 9 4 9 8]
  [6 1 6 3 3]
  [9 7 4 3 1]]

 [[6 3 2 4 6]
  [0 9 9 9 8]
  [8 6 5 4 6]]]
[[[ 5. 10.  5. 10.  9.]
  [ 7.  2.  7.  4.  4.]
  [10.  8.  5.  4.  2.]]

 [[ 7.  4.  3.  5.  7.]
  [ 1. 10. 10. 10.  9.]
  [ 9.  7.  6.  5.  7.]]]



### 12. Multiply a and c. Assign the result to e.


In [61]:
e = a * c
print(c)
print (a) 
print(e)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[4 9 4 9 8]
  [6 1 6 3 3]
  [9 7 4 3 1]]

 [[6 3 2 4 6]
  [0 9 9 9 8]
  [8 6 5 4 6]]]
[[[4. 9. 4. 9. 8.]
  [6. 1. 6. 3. 3.]
  [9. 7. 4. 3. 1.]]

 [[6. 3. 2. 4. 6.]
  [0. 9. 9. 9. 8.]
  [8. 6. 5. 4. 6.]]]




### 13. Does e equal to a? Why or why not?


In [60]:
print(e == a)

#yes because c was an array of Ones 

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [63]:
d_max = np.max(d)
d_min = np.min(d)
d_mean= np.mean(d)
print (d_max,d_min,d_mean)


10.0 1.0 6.4



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [65]:
f = np.empty((2,3,5))
print(f)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [66]:
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print (f)

[[[ 25. 100.  25. 100.  75.]
  [ 75.  25.  75.  25.  25.]
  [100.  75.  25.  25.  25.]]

 [[ 75.  25.  25.  25.  75.]
  [  0. 100. 100. 100.  75.]
  [ 75.  75.  25.  25.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [67]:
print(d)
print (f)


[[[ 5. 10.  5. 10.  9.]
  [ 7.  2.  7.  4.  4.]
  [10.  8.  5.  4.  2.]]

 [[ 7.  4.  3.  5.  7.]
  [ 1. 10. 10. 10.  9.]
  [ 9.  7.  6.  5.  7.]]]
[[[ 25. 100.  25. 100.  75.]
  [ 75.  25.  75.  25.  25.]
  [100.  75.  25.  25.  25.]]

 [[ 75.  25.  25.  25.  75.]
  [  0. 100. 100. 100.  75.]
  [ 75.  75.  25.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [70]:
f[f == 100] = "A"
f[f == 75] = "B"
f[f == 50] = "C"
f[f == 25] = "D"
f[f == 0] = "F" 


ValueError: could not convert string to float: 'A'